import type {
  ArticleCategory,
  ArticleRecord,
  ContentBlock,
  DonationsInfo,
  EventRecord,
  SiteSettings,
  VideoCategory,
  VideoRecord,
} from "@/types/content";
import { defaultDonationsInfo, defaultSiteSettings } from "@/lib/site";

const articleCategories: ArticleCategory[] = [
  { id: "cat-shema", name: "Estudio", slug: "estudio", description: "Enseñanzas y reflexiones bíblicas." },
  { id: "cat-historia", name: "Historia", slug: "historia", description: "Memoria, contexto y tradición." },
  { id: "cat-comunidad", name: "Comunidad", slug: "comunidad", description: "Vida comunitaria y anuncios." },
];

const videoCategories: VideoCategory[] = [
  { id: "vid-cat-estudio", name: "Estudio", slug: "estudio" },
  { id: "vid-cat-ensenanzas", name: "Enseñanzas", slug: "ensenanzas" },
  { id: "vid-cat-eventos", name: "Eventos", slug: "eventos" },
];

const sampleBlocks: ContentBlock[] = [
  {
    id: "b1",
    type: "paragraph",
    text: "La Comunidad Natzratim nace para honrar la memoria, fortalecer el estudio y abrir un espacio de encuentro con dignidad y reverencia.",
  },
  {
    id: "b2",
    type: "quote",
    text: "La sabiduría se construye con estudio constante, humildad y servicio a la comunidad.",
    cite: "Línea guía comunitaria",
  },
  {
    id: "b3",
    type: "verse",
    text: "ועשית ככל אשר יורוך",
    reference: "Texto de reflexión",
  },
];

const articles: ArticleRecord[] = [
  {
    id: "art-1",
    slug: "la-memoria-viva-del-estudio",
    title: "La memoria viva del estudio",
    excerpt: "Una reflexión sobre la transmisión, la disciplina y el amor por la enseñanza.",
    content: sampleBlocks,
    featured_image_url: "/brand/natzratim-logo.jpg",
    featured_image_alt: "Logo de la Comunidad Natzratim",
    category: articleCategories[0],
    category_id: articleCategories[0].id,
    author_name: "Administración Natzratim",
    published: true,
    published_at: "2026-05-10T10:00:00.000Z",
    seo_title: "La memoria viva del estudio",
    seo_description: "Reflexión sobre estudio, transmisión y comunidad.",
    reading_time_minutes: 5,
    created_at: "2026-05-10T10:00:00.000Z",
    updated_at: "2026-05-10T10:00:00.000Z",
  },
  {
    id: "art-2",
    slug: "jerusalen-y-la-vida-comunitaria",
    title: "Jerusalén y la vida comunitaria",
    excerpt: "Cómo la ciudad santa inspira orden, continuidad y servicio.",
    content: sampleBlocks,
    featured_image_url: null,
    featured_image_alt: null,
    category: articleCategories[1],
    category_id: articleCategories[1].id,
    author_name: "Maestra de estudio",
    published: true,
    published_at: "2026-05-18T10:00:00.000Z",
    seo_title: "Jerusalén y la vida comunitaria",
    seo_description: "Jerusalén como símbolo de estudio y comunidad.",
    reading_time_minutes: 4,
    created_at: "2026-05-18T10:00:00.000Z",
    updated_at: "2026-05-18T10:00:00.000Z",
  },
];

const videos: VideoRecord[] = [
  {
    id: "vid-1",
    slug: "estudio-de-la-semana",
    title: "Estudio de la semana",
    excerpt: "Encuentro semanal con enfoque en contexto histórico y aplicación práctica.",
    youtube_url: "https://youtu.be/dQw4w9WgXcQ",
    youtube_id: "dQw4w9WgXcQ",
    thumbnail_url: "https://img.youtube.com/vi/dQw4w9WgXcQ/hqdefault.jpg",
    category: videoCategories[0],
    category_id: videoCategories[0].id,
    published: true,
    published_at: "2026-05-21T10:00:00.000Z",
    seo_title: "Estudio de la semana",
    seo_description: "Video semanal para la comunidad.",
    content: sampleBlocks,
    created_at: "2026-05-21T10:00:00.000Z",
    updated_at: "2026-05-21T10:00:00.000Z",
  },
  {
    id: "vid-2",
    slug: "sabiduria-y-servicio",
    title: "Sabiduría y servicio",
    excerpt: "Una enseñanza sobre disciplina, carácter y pertenencia.",
    youtube_url: "https://youtu.be/dQw4w9WgXcQ",
    youtube_id: "dQw4w9WgXcQ",
    thumbnail_url: "https://img.youtube.com/vi/dQw4w9WgXcQ/hqdefault.jpg",
    category: videoCategories[1],
    category_id: videoCategories[1].id,
    published: true,
    published_at: "2026-05-29T10:00:00.000Z",
    seo_title: "Sabiduría y servicio",
    seo_description: "Contenido para fortalecer la comunidad.",
    content: sampleBlocks,
    created_at: "2026-05-29T10:00:00.000Z",
    updated_at: "2026-05-29T10:00:00.000Z",
  },
];

const events: EventRecord[] = [
  {
    id: "evt-1",
    slug: "shabat-comunitario",
    title: "Shabat comunitario",
    excerpt: "Reunión semanal de enseñanza y comunión.",
    content: sampleBlocks,
    event_date: "2026-06-20T00:00:00.000Z",
    start_time: "18:30",
    end_time: "20:30",
    location: "Casa comunitaria",
    location_label: "Jerusalén",
    category: "Festividad",
    published: true,
    published_at: "2026-06-01T10:00:00.000Z",
    seo_title: "Shabat comunitario",
    seo_description: "Encuentro semanal de estudio y comunidad.",
    created_at: "2026-06-01T10:00:00.000Z",
    updated_at: "2026-06-01T10:00:00.000Z",
  },
  {
    id: "evt-2",
    slug: "conmemoracion-de-judea",
    title: "Conmemoración de Judea",
    excerpt: "Jornada histórica y espiritual con enfoque de estudio.",
    content: sampleBlocks,
    event_date: "2026-07-04T00:00:00.000Z",
    start_time: "17:00",
    end_time: "19:00",
    location: "Auditorio principal",
    location_label: "Mesa redonda",
    category: "Estudio",
    published: true,
    published_at: "2026-06-05T10:00:00.000Z",
    seo_title: "Conmemoración de Judea",
    seo_description: "Encuentro de reflexión histórica.",
    created_at: "2026-06-05T10:00:00.000Z",
    updated_at: "2026-06-05T10:00:00.000Z",
  },
];

export const mockData = {
  settings: defaultSiteSettings,
  donations: defaultDonationsInfo,
  articleCategories,
  videoCategories,
  articles,
  videos,
  events,
};
